### PR TITLE
Vet clinic database: query and update animals table

### PR DESCRIPTION
**Pull request by Camilovelag**
# Good day! 🌤️

This pull request is intended to create a Vet clinic DB.

## 🛠️ Changes made

✔️ Add a column `species` of type `string` to your `animals` table.
✔️ Insert new `animals`.
✔️ Add transactions (screenshots below).
✔️ Add grouped queries to answer questions (screenshots below).

I'm expecting feedback.

Happy coding!  👏👏👏

Update `species` values:

query1

Delete the whole table:

query2

Fix non-positive weight value bug:

query3

Answer questions:

query4

### CODE REVIEW

**Review by CollinsTatang — COMMENTED** [review]
Hi @Camilovelag 

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has an outdated README file

- [ ]  Please check out the newly updated [Microverse README Template](https://github.com/microverseinc/readme-template) and use it to update your current README file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Camilovelag** [comment]
## Hi @CollinsTatang 👋 
I'm using the README template specified for this [project](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md). It is needed to change de README file after all?
Thanks!

**Comment by CollinsTatang** [comment]
> ## Hi @CollinsTatang 
> I'm using the README template specified for this [project](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md). It is needed to change de README file after all? Thanks!

Hi @Camilovelag 
Ok now I understand 

Thank you

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Camilovelag** [comment]
Thanks, @CollinsTatang!
Time to take a well-deserved rest 😄

**Pull request merged**
